import type { MetadataRoute } from "next";

// Served at /manifest.webmanifest; Next auto-adds <link rel="manifest">. Icons are
// generated by scripts/gen-icons.mjs from the brand mark (the logo's "4" glyph).
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "4Pie Labs — Client Portal",
    short_name: "4Pie Labs",
    description: "Your 4Pie Labs client portal.",
    start_url: "/dashboard",
    display: "standalone",
    background_color: "#f7f6f2",
    theme_color: "#f7f6f2",
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
